worker_processes 1;

events { worker_connections 1024; }

http {
    sendfile on;

    upstream auth_service {
        server auth-service:3001;
    }

    upstream order_service {
        server order-service:3002;
    }

    upstream payment_service {
        server payment-service:3003;
    }

    upstream orchestrator_service {
        server orchestrator-service:8000;
    }

    server {
        listen 8000;

        location /auth/ {
            proxy_pass http://auth_service/;
        }

        location /orders/ {
            proxy_pass http://order_service/;
        }

        location /payments/ {
            proxy_pass http://payment_service/;
        }

        location /orchestrator/ {
            proxy_pass http://orchestrator_service/;
        }
    }
}
